# https://taskfile.dev

version: '3'

vars:
  BINARY_NAME: wrldbldr-player
  RUST_LOG: debug

env:
  RUST_BACKTRACE: 1
  RUST_LOG: '{{.RUST_LOG}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Setup tasks
  setup:
    desc: Install all dependencies (npm + cargo)
    cmds:
      - npm install
      - cargo fetch

  # CSS tasks
  css:
    desc: Build Tailwind CSS
    cmds:
      - npm run build:css

  css:watch:
    desc: Watch and rebuild CSS on changes
    cmds:
      - npm run watch:css

  # Desktop tasks
  desktop:
    desc: Run desktop app in development mode
    deps: [css]
    cmds:
      - cargo run

  desktop:build:
    desc: Build desktop app in debug mode
    deps: [css]
    cmds:
      - cargo build

  desktop:release:
    desc: Build desktop app in release mode
    deps: [css]
    cmds:
      - cargo build --release

  # Web tasks
  web:
    desc: Start web development server with hot reload
    cmds:
      - trunk serve

  web:build:
    desc: Build web app for production
    cmds:
      - trunk build --release

  web:preview:
    desc: Preview production web build locally
    deps: [web:build]
    cmds:
      - cd dist && python3 -m http.server 8080

  # Android tasks (placeholder - requires additional setup)
  android:
    desc: Build for Android (requires setup)
    cmds:
      - |
        echo "Android build requires additional setup:"
        echo "1. Install Android SDK and NDK"
        echo "2. Install dioxus-cli with android support"
        echo "3. Configure ANDROID_HOME and ANDROID_NDK_HOME"
        echo ""
        echo "For mobile testing, use 'task web' which works on mobile browsers."

  # Development workflows
  dev:
    desc: Start full development environment (CSS watch + desktop)
    cmds:
      - task: css
      - |
        # Run CSS watcher in background
        npm run watch:css &
        CSS_PID=$!
        trap "kill $CSS_PID 2>/dev/null" EXIT
        cargo run

  dev:web:
    desc: Start full web development environment
    cmds:
      - trunk serve

  # Code quality tasks
  check:
    desc: Check for compilation errors
    cmds:
      - cargo check

  test:
    desc: Run all tests
    cmds:
      - cargo test

  lint:
    desc: Run clippy linter
    cmds:
      - cargo clippy -- -D warnings

  fmt:
    desc: Format code (Rust + check Tailwind config)
    cmds:
      - cargo fmt

  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt -- --check

  # Documentation
  docs:
    desc: Generate and open documentation
    cmds:
      - cargo doc --open --no-deps

  # Cleanup tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
      - rm -rf dist/
      - rm -rf .cargo/

  clean:all:
    desc: Clean everything including node_modules and generated CSS
    cmds:
      - task: clean
      - rm -rf node_modules/
      - rm -f assets/css/output.css

  clean:cache:
    desc: Clean trunk and wasm caches
    cmds:
      - rm -rf .trunk/
      - rm -rf pkg/

  # CI/CD tasks
  ci:
    desc: Run all CI checks
    cmds:
      - task: setup
      - task: css
      - task: fmt:check
      - task: lint
      - task: test
      - task: desktop:build

  ci:web:
    desc: Run CI for web build
    cmds:
      - task: setup
      - task: web:build

  # Build all platforms
  build:all:
    desc: Build for all platforms (desktop + web)
    cmds:
      - task: desktop:release
      - task: web:build

  # Utility tasks
  deps:
    desc: Show Rust dependency tree
    cmds:
      - cargo tree

  deps:npm:
    desc: Check for outdated npm packages
    cmds:
      - cmd: npm outdated
        ignore_error: true

  deps:outdated:
    desc: Check for outdated Rust dependencies
    cmds:
      - cmd: cargo outdated
        ignore_error: true

  size:
    desc: Show binary sizes for all builds
    deps: [desktop:release]
    cmds:
      - echo "Desktop binary:"
      - cmd: ls -lh target/release/{{.BINARY_NAME}}
        ignore_error: true
      - echo ""
      - echo "Web build (if exists):"
      - cmd: du -sh dist/
        ignore_error: true

  # Asset management
  assets:
    desc: List all assets
    cmds:
      - find assets -type f | head -50

  assets:icons:
    desc: Generate app icons (placeholder)
    cmds:
      - |
        echo "Icon generation requires source image."
        echo "Place a 1024x1024 PNG at assets/icons/source.png"
        echo "Then run icon generation tool."
